language: objective-c
script:
  - xctool -workspace UnrarKit.xcworkspace -scheme UnrarKit -configuration Release analyze test
  - xctool -workspace UnrarKit.xcworkspace -scheme UnrarKit -sdk macosx10.7
  - xctool -workspace UnrarKit.xcworkspace -scheme UnrarExample -configuration Release -sdk iphonesimulator analyze
  - xctool -workspace UnrarKit.xcworkspace -scheme UnrarExample -sdk iphonesimulator5.0
  - ./Scripts/cocoapod-validate.sh

# Turn on Docker, container-based infrastructure
sudo: false